#!/bin/bash

config=/home/$(whoami)/.config/

if [ -z "$1" ]; then
	cd $config/confchanger
	killall wofi
	sh confchanger $(ls -d */ | sed 's/\///g' | wofi -d)
else
	cd $config/confchanger
	cp -r $config/confchanger/$1/* $config
	killall waybar & killall wpaperd
	waybar & wpaperd -d
fi