#!/bin/bash

config=/home/$(whoami)/.config/

if [ -z "$1" ]; then
	cd $config/confchanger
	killall wofi
	sh confchanger $(ls -d */ | sed 's/\///g' | wofi -d)
else
	cd $config/confchanger
	cp -r $config/confchanger/$1/* $config
	cat $config/confchanger/icons.jsonc >> $config/waybar/config.jsonc
	killall waybar & killall wpaperd & killall swaync
	# Wait until the processes have been shut down
	while pgrep -x waybar >/dev/null; do sleep 1; done
	while pgrep -x wpaperd >/dev/null; do sleep 1; done
	while pgrep -x swaync >/dev/null; do sleep 1; done
	waybar & wpaperd -d & swaync
fi