github.com:
    users:
        Capita1:
            oauth_token: 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
    git_protocol: https
    user: Capita1
    oauth_token: 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
