#!/bin/bash

#se wofi estiver rodando
if pgrep -x "wofi" > /dev/null
then
	killall wofi
	exit 1
fi

#se $1 estiver vazio
if [ -z "$1" ]; then
	wofi -S drun	
fi

#se $1 igual a area
if [ "$1" = "area" ]; then
	cliphist list | wofi --dmenu | cliphist decode | wl-copy
fi

#se $1 igual a altab
if [ "$1" = "altab" ]; then
	janela=$(hyprctl clients | sed '/class/!d' | cut -d ':' -f 2 | wofi -S dmenu --columns=2 --height=150 --width=500 --location=0 --prompt=Apps)
	#se tem algo em $janela
	if [ -n "$janela" ]; then
		hyprctl dispatch focuswindow $janela
	fi
fi

#se $1 igual a logout
if [ "$1" = "logout" ]; then
	choice=$(echo -e "0: Sair 󰍃\n1: Desligar 󰐥\n2: Reiniciar 󰜉" | wofi -d | cut -d ':' -f 1)
	case "$choice" in
	  0) killall Hyprland & ;;
	  1) systemctl poweroff & ;;
	  2) systemctl reboot & ;;
	esac
fi
if [ "$1" = "temas" ]; then
	config=/home/$(whoami)/.config/
	if [ -z "$2" ]; then
		cd $config/hypr/temas/
		sh $config/hypr/scripts/menus $1 $(ls -d */ | sed 's/\///g' | wofi -d --width=200 --height=200)
	else
		cd $config/hypr/temas/$2
		ln -r -s -f * $config
		cp hypr/style.conf ../../
		killall waybar ; killall wpaperd ; killall swaync
		waybar & wpaperd -d & swaync
	fi
fi