#!/bin/bash
player='playerctl --player vlc'
#se $1 não tiver vazio
if [ -n "$1" ]; then
	$player $1 $2	
fi
if [ "$($player status)" = "Playing" ]; then
	ico="󰏤"
fi
if [ "$($player status)" = "Paused" ]; then
	ico="󰐊"
fi
artista=$($player metadata --format "{{ artist }}")
titulo=$($player metadata --format "{{ title }}")
album=$($player metadata --format "{{ album }}")
volume=$(echo $( awk "BEGIN { print int($($player volume)*100)}"))
duracao=$($player metadata --format "{{ duration(mpris:length) }}")
notify-send -e "$(echo -e "$ico $artista - $titulo\n\t $volume%\t󰀥 $album\t󱎫 $duracao")" -h string:x-canonical-private-synchronous:anything -t 2000
clear
echo -e "$ico $artista - $titulo\n $volume%\t󰀥 $album\t󱎫 $duracao"
