#!/bin/bash

#se wofi estiver rodando
if pgrep -x "wofi" > /dev/null
then
	killall wofi
fi

#se $1 estiver vazio
if [ -z "$1" ]; then
	wofi -S drun	
fi

#se $1 igual a altab
if [ "$1" = "altab" ]; then
	janela=$(hyprctl clients | sed '/class/!d' | cut -d ':' -f 2 | wofi -S dmenu --columns=2 --height=250 --width=250 --location=0 --hide_search=true --prompt=Apps)
	#se tem algo em $janela
	if [ -n "$janela" ]; then
		hyprctl dispatch focuswindow $janela
	fi
fi

#se $1 igual a logout
if [ "$1" = "logout" ]; then
	choice=$(echo -e "0: Sair 󰍃\n1: Desligar 󰐥\n2: Reiniciar 󰜉" | wofi -d | cut -d ':' -f 1)
	case "$choice" in
	  0) killall Hyprland & ;;
	  1) systemctl poweroff & ;;
	  2) systemctl reboot & ;;
	esac
fi
if [ "$1" = "temas" ]; then
	apps=("waybar" "wpaperd" "swaync") ; len=${#apps[@]}
	config=/home/$(whoami)/.config/
	cd $config/hypr/temas
	if [ -z "$2" ]; then
		sh $config/hypr/menus temas $(ls -d */ | sed 's/\///g' | wofi -d)
	else
		cp -r $2/* $config
		cat icons.jsonc >> $config/waybar/config.jsonc
		killall waybar ; killall wpaperd ; killall swaync
		waybar & wpaperd -d & swaync
	fi
fi