#!/bin/bash
killall wofi
#se $1 estiver vazio
if [ -z "$1" ]; then
	wofi -S drun
fi

#se $1 igual a altab
if [ "$1" = "altab" ]; then
	janela=$(hyprctl clients | sed '/class/!d' | cut -d ':' -f 2 | wofi -S dmenu --columns=10 --height=100 --width=500 --location=0 --hide_search=true --prompt=Apps)
	#se tem algo em $janela
	if [ -n "$janela" ]; then
		hyprctl dispatch focuswindow $janela
	fi
fi

#se $1 igual a logout
if [ "$1" = "logout" ]; then
	choice=$(echo -e "0: Logout 󰍃\n1: Desligar 󰐥\n2: Reiniciar 󰜉" | wofi -d | cut -d ':' -f 1)
	case "$choice" in
	  0) killall Hyprland & ;;
	  1) systemctl poweroff & ;;
	  2) systemctl reboot & ;;
	esac
fi