#Configuração de entrada
input {
    kb_layout = br
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    numlock_by_default = true
    follow_mouse = 1
    sensitivity = 1 
    accel_profile = flat
    touchpad {
        natural_scroll = false
    }
}
