windowrule = rounding 0, match:class Audacious
#audio
windowrule = workspace special:audio silent ,match:class (org.pulseaudio.pavucontrol)
workspace = special:audio, on-created-empty:org.pulseaudio.pavucontrol
#rmpc
workspace = special:musica, on-created-empty:kitty rmpc
workspace = 5, on-created-empty:obsidian

#monitors
workspace = 1,monitor:DP-1
workspace = 2,monitor:DP-1
workspace = 3,monitor:DP-1
workspace = 4,monitor:DP-1
workspace = 5,monitor:DP-1
workspace = 6,monitor:HDMI-A-1,border_size 0,gapsin:0,gapsout:0,rounding 0
workspace = 7,monitor:HDMI-A-1
workspace = 8,monitor:HDMI-A-1
workspace = 9,monitor:HDMI-A-1
workspace = 10,monitor:HDMI-A-1

#LAYER
#swaync
layerrule = blur on,  match:namespace swaync-control-center
layerrule = ignore_alpha 0, match:namespace swaync-control-center
layerrule = blur on,  match:namespace swaync-notification-window
layerrule = ignore_alpha 0, match:namespace swaync-notification-window
#waybar
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace waybar
#wofi
layerrule = blur on, match:namespace wofi
layerrule = ignore_alpha 0, match:namespace wofi
