#!/bin/bash

#Cut (without re-encoding)
 ffmpeg -i input.mp4 -ss 00:00:12 -to 00:02:30 -c copy output.mp4

#Rotate by 180°
ffmpeg -display_rotation 180 -i input.mp4 -codec copy output.mp4

#Scale resolution of a video to 1920 pixels (keep aspect ratio)
ffmpeg -i input.mp4 -vf "scale=1920:-2" output.mp4

#Fade first 5 seconds of a video
ffmpeg -i input.mp4 -vf "fade=t=in:st=0:d=5" out.mp4

infos=$(slurp)
dh=$(echo $infos | cut -d "," -f 1)
dv=$(echo $infos | cut -d "," -f 2 | cut -d " " -f 1)
th=$(echo $infos | cut -d "x" -f 1 | cut -d " " -f 2)
tv=$(echo $infos | cut -d "x" -f 2 )
echo -e "distancia horizontal=$dh\ndistancia vertical=$dv\ntamanho horizontal=$th\ntamanho vertical=$tv  "
video=$(ls |wofi -d )
#$(echo -e "ffmpeg -i $video -vf "crop=$th:$tv:$dh:$dv" -c:a copy cortado.mp4")
printf "ffmpeg -i \"%s\" -vf \"crop=%s:%s:%s:%s\" -c:a copy cortado.mp4"\
	       "$video" "$th" "$tv" "$dh" "$dv"