#!/bin/bash
wallpapers=/home/$(whoami)/Imagens/Wallpapers/
monitor="[any]"
cd $wallpapers

sele=$(echo -e "0: 󰋩 Escolher um Wallpaper \n1: 󰉏 Escolher uma pasta\n2: 󰋹 Todos" | wofi -d | cut -d ':' -f 1)
case "$sele" in		
	0) foto="$(find . -type f | cut -d '/' -f 2,3,4,5 | wofi -d)";;
	1) foto="$(ls -h | wofi -d)";;
	2) foto="todos"
esac

if [ -d "$foto" ];then #se $foto é diretorio
	escolha="$monitor\npath = \"$wallpapers$foto\"\nduration=\"5m\"\nmode=\"stretch\""
else	#se não é diretório
	escolha="$monitor\npath = \"$wallpapers$foto\"\nmode=\"stretch\""
fi
if [ "$sele" = "2" ]; then #se escolhi todos
	escolha="$monitor\npath = \"$wallpapers\"\nduration=\"5m\"\nmode=\"stretch\""
fi

#se $foto não estiver vazio
if [ -n "$foto" ]; then
	echo -e "$escolha" > ~/.config/wpaperd/config.toml
	killall wpaperd 
	sleep 1
	wpaperd
	exit 0
else
	exit 0
fi