#!/bin/bash
opcoes="apps\nbaixar\narea\ntela\naltab\nlogout\ntemas"

#se wofi estiver rodando
if pgrep -x "wofi" > /dev/null
then
	killall wofi
	exit 1
fi

#se $1 estiver vazio
if [ -z "$1" ]; then
	sh ~/.config/hypr/scripts/menus $(echo -e $opcoes | wofi -d --width=200 --height=150)  
fi

#se $1 igual a apps
if [ "$1" = "apps" ]; then
	wofi -S drun	
fi
#se $1 igual a baixar
if [ "$1" = "baixar" ]; then
	if [ -z "$2" ]; then
	tipo=$(echo -e "audio\nvideo" | wofi -d --width=200 --height=150 ) 
	else
	tipo=$2
	fi
	if [ -z "$3" ]; then
	url=$(cliphist list | wofi -d | cliphist decode)
	else
	url=$3
	fi
	if [ "$tipo" = "audio" ]; then
		cd ~/Músicas/
		yt-dlp -f 'bestaudio' --extract-audio --audio-format mp3 --embed-metadata "$url"
	fi
	if [ "$tipo" = "video" ]; then
		cd ~/Videos/
		yt-dlp -f 'bestvideo+bestaudio/bestvideo+bestaudio' --merge-output-format mp4 --embed-metadata "$url"
	fi
fi

#se $1 igual a area
if [ "$1" = "area" ]; then
	cliphist list | wofi --dmenu | cliphist decode | wl-copy
fi

#se $1 igual a tela
if [ "$1" = "tela" ]; then
	mon1=$(hyprctl monitors | grep -e 'availableModes' | cut -d ':' -f 2 | tr " " "\n" | wofi -d)
	if [ -n "$mon1" ]; then 
		echo "monitor=eDP-1,$mon1,0x0,1" | cat > ~/.config/hypr/edp.conf
	else
		exit 1	
	fi
fi

#se $1 igual a altab
if [ "$1" = "altab" ]; then
	janela=$(hyprctl clients | sed '/class/!d' | cut -d ':' -f 2 | wofi -d --columns=2 --height=100 --width=400 --location=0 --prompt=Apps)
	#se tem algo em $janela
	if [ -n "$janela" ]; then
		hyprctl dispatch focuswindow "$janela"
	fi
fi

#se $1 igual a logout
if [ "$1" = "logout" ]; then
	choice=$(echo -e "0: Sair 󰍃\n1: Desligar 󰐥\n2: Reiniciar 󰜉" | wofi -d --width=200 --height=150 | cut -d ':' -f 1)
	case "$choice" in
	  0) hyprctl dispatch exit & ;;
	  1) systemctl poweroff & ;;
	  2) systemctl reboot & ;;
	esac
fi
#se $1 igual a temas
if [ "$1" = "temas" ]; then
	config=/home/$(whoami)/.config/
	#se tem algo em $2
	if [ -n "$2" ]; then
		cd $config/hypr/temas/$2
		ln -rsf * $config
		cp hypr/style.conf ../../
		killall waybar ; killall wpaperd ; killall swaync
		waybar & wpaperd -d & swaync
	else
		cd $config/hypr/temas/
		sh $config/hypr/scripts/menus $1 $(ls -d */ | sed 's/\///g' | wofi -d --width=200 --height=200)
	fi
fi