#!/bin/bash

player='playerctl --player=vlc'
local="/home/$(whoami)/.config/hypr/scripts/musica"
#se $1 igual player
if [ "$1" = "player" ]; then
	pla=$(echo -e "player='playerctl --player=$(playerctl --list-all | wofi -d )'")
	sed -i "3s/.*/$pla/" $local
fi
#se $1 igual select
if [ "$1" = "select" ]; then
	if [ -z "$2" ]; then #se $2 estiver vazio
		sh $local select /home/$(whoami)/Músicas
	else
		if [ -d "$2" ]; then #se $2 é diretorio
			killall wofi
			atual=$(echo "$2" | cut -d "/" -f 5,6)
			sele=$(echo -e "0: 󰐊 Tocar $atual\n1:  Abrir $atual" | wofi -d | cut -d ':' -f 1)
			case "$sele" in
				0) killall vlc ; cvlc -Z "$2" ; exit 0 ;;
				1) cd "$2" ; sh $local select "$2/$(ls -h | wofi -d)" ; exit 0 ;;
			esac
		fi
		if [ -f "$2" ]; then #se $2 é arquivo
			killall vlc ; cvlc "$2" ; exit 0
		fi
	fi
elif [ -n "$1" ]; then #se $1 não está vazio
	$player $1 $2	
fi
if [ "$($player status)" = "Playing" ]; then
	ico="󰏤"
fi
if [ "$($player status)" = "Paused" ]; then
	ico="󰐊"
fi
artista=$($player metadata --format "{{ artist }}")
titulo=$($player metadata --format "{{ title }}")
album=$($player metadata --format "{{ album }}")
volume=$(echo $( awk "BEGIN { print int($($player volume)*100)}"))
duracao=$($player metadata --format "{{ duration(mpris:length) }}")
#se $1 igual a tocando
if [ "$1" = "tocando" ]; then
	echo -e "$ico"
	exit 0
fi
#se $1 igual a mais
if [ "$1" = "mais" ]; then
	text="$titulo\n$artista\n$album"
	tooltip="󰕾 $volume%"
	printf "{ \"text\": \"%s\", \"tooltip\": \"%s\", \"class\": \"%s\" }\n" \
	       "$text" "$tooltip" 
	exit 0
fi
#se $1 está vazio
if [ -z "$1" ]; then
	text="$titulo - $artista"
	tooltip="󰕾 $volume%"
	printf "{ \"text\": \"%s\", \"tooltip\": \"%s\", \"class\": \"%s\" }\n" \
	       "$text" "$tooltip" 
	exit 0
fi
notify-send -e "$(echo -e "$ico $artista - $titulo\n\t $volume%\t󰀥 $album\t󱎫 $duracao")" -h string:x-canonical-private-synchronous:anything -t 2000