#!/bin/bash

player='playerctl --player=vlc'
local="/home/$(whoami)/.config/hypr/scripts/musica"
#se $1 igual player
if [ "$1" = "player" ]; then
	pla=$(echo -e "player='playerctl --player=$(playerctl --list-all | wofi -d )'")
	sed -i "3s/.*/$pla/" $local
fi
#se $1 igual select
if [ "$1" = "select" ]; then
	if [ -z "$2" ]; then #se $2 estiver vazio
		sh $local select /home/$(whoami)/Músicas
	else
		killall wofi
		cd "$2"
		sele=$(echo -e "0:  Tocar música \n1: 󱧺 Tocar pasta\n2: 󰐑 Tocar playlist\n3: 󰴙 Tocar todas\n4: 󰥠 Mudar player" | wofi -d | cut -d ':' -f 1)
		case "$sele" in		
			0) musica="$(find . -type f | cut -d '/' -f 2,3,4,5 | wofi -d)";;
			1) musica="$(ls -h | wofi -d)";;
			2) musica=".playlists/$(ls .playlists | wofi -d)";;
			3) ln -rsf */* .todas/ ; musica=".todas";;
			4) $local player;;
		esac
		if [ "$musica" = ".playlists/" ]; then
			exit 0
		fi
		if [ -n "$musica" ]; then
			killall vlc 
			cvlc -Z "$musica"
			exit 0
		fi
	fi
elif [ -n "$1" ]; then #se $1 não está vazio
	$player $1 $2
fi
if [ "$($player status)" = "Playing" ]; then
	ico="󰏤"
fi
if [ "$($player status)" = "Paused" ]; then
	ico="󰐊"
fi
artista=$($player metadata --format "{{ artist }}")
titulo=$($player metadata --format "{{ title }}")
album=$($player metadata --format "{{ album }}")
volume=$(echo $( awk "BEGIN { print int($($player volume)*100)}"))
duracao=$($player metadata --format "{{ duration(mpris:length) }}")
#se $1 igual a tocando
if [ "$1" = "tocando" ]; then
	echo -e "$ico"
	exit 0
fi
tooltip="󰕾 $volume%"
#se $1 igual a mais
if [ "$1" = "mais" ]; then
	text="$titulo\n$artista\n$album"
	printf "{ \"text\": \"%s\", \"tooltip\": \"%s\",}\n" \
	       "$text" "$tooltip" "aaa"
	exit 0
fi
#se $1 está vazio
if [ -z "$1" ]; then
	text="$titulo\n$artista"
	printf "{ \"text\": \"%s\", \"tooltip\": \"%s\",}\n" \
	       "$text" "$tooltip"
	exit 0
fi
notify-send -e "$(echo -e "$ico $artista - $titulo\n$tooltip\t󰎅 $album\t󱎫 $duracao")" -h string:x-canonical-private-synchronous:anything -t 1000
sleep 1
sh $local